### ISSUE TITLE
Add support for DefinedTerm

### ISSUE THREAD

**Issue by JohJohan** [spatie/schema-org#108]
Right now we dont support https://schema.org/DefinedTerm can this be implemented?

I can also work on this if we want it let me know.

**Comment by Gummibeer** [comment]
Hey, it's marked as *pending*
> This term is proposed for full integration into Schema.org, pending implementation feedback and adoption from applications and websites.

As long as it isn't part of https://github.com/schemaorg/schemaorg/blob/master/data/schema.rdfa it won't find it's way in this library.
> The code in src is generated from Schema.org's RDFa standards file, so it provides objects and methods for the entire core vocabulary.

I've triggered a new generation and the `DefinedTerm` is only implemented as a type hint but not as it's own type. Which is a very common problem with these pending types in schema.org standard. It's used for `\Spatie\SchemaOrg\JobPosting::skills()` already - so if I would release it now the `skills()` method is removed from interface and class and only added as a doc-tag method line.
```
@method static skills($skills) The value should be instance of pending types DefinedTerm|DefinedTerm[]|string|string[]
```
That's because of our check vor valid type-hints and moving methods with invalid/pending type hints into the annotations.
https://github.com/spatie/schema-org/blob/bd91c6202543079df7af0d97c84bf3ac3875bbd9/generator/TypeCollection.php#L22-L28

**Comment by gavinhewitt** [comment]
Sorry to bring this up again, but I'm wondering when you are building a dictionary of some sort, how would you define the terms if DefinedTerm is not available as type?

**Comment by Gummibeer** [comment]
hey @gavinhewitt ,
the package won't receive any more updates until a new maintainer is found. 
https://github.com/spatie/schema-org#notice

But the package and code is extendible - so you can create your own types in your own project.

Or if you feel comfortable with migrating the generator to the new schema.org v8 & v9 I will happily guide you.

**Comment by gavinhewitt** [comment]
> hey @gavinhewitt ,
> the package won't receive any more updates until a new maintainer is found.
> https://github.com/spatie/schema-org#notice
> 
> But the package and code is extendible - so you can create your own types in your own project.
> 
> Or if you feel comfortable with migrating the generator to the new schema.org v8 & v9 I will happily guide you.

I found that the FAQPage type actually covers my needs. Thanks!
