### ISSUE TITLE
Add `gtin` property to products

### ISSUE THREAD

**Issue by sascha-egerer** [spatie/schema-org#135]
http://schema.org/gtin was added schema.org 3.8

See https://github.com/schemaorg/schemaorg/issues/1244#issuecomment-635601340

**Comment by sascha-egerer** [comment]
Ok, did not notice that the code is generated. Looks like the property is missing in the official schema

**Comment by Gummibeer** [comment]
Hey,
I will check if we can regenerate it.
Right now we will have to decide how we proceed generating the code because we always had problems with not really well maintained RDFa and it's also dropped now. #133 

But I will keep this issue open for now and check what we can do.
In fact you can add every property you want by using the `setProperty()` method.

**Comment by Gummibeer** [comment]
So far the schema.org documentation, RDFa, changelog and issues are different/conflicting like usual ...

> This term is proposed for full integration into Schema.org, pending implementation feedback and adoption from applications and websites.
> - https://schema.org/gtin @ 2020-07-16

> http://schema.org/gtin was added schema.org 3.8
> - https://github.com/schemaorg/schemaorg/issues/1244 @ 2020-05-28

> - https://schema.org/version/3.8/#term_gtin @ 2019-07-01

The v7.04 RDFa does not contain a `gtin` definition - only `GTIN-8/12/13/14`.
> It is recommended to additionally provide strong product identifiers via the gtin8/gtin13/gtin14 and mpn properties.
> - https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/releases/7.04/schema.rdfa

Even the named `v3.8` release doesn't contain a `gtin` definition ...
https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/releases/3.8/schema.rdfa

And also the next release `v8.0` we will support in near future does only contain the GTIN-8/12/13/14 definitions.
https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/releases/8.0/schema.rdfa

I'm sorry but it seems like the GTIN is a pending type - even if they say that it's already implemented. But in question I trust the RDFa files more than any issue comments.

Primary because it's still listed in the `pending.rdf` files:
* v3.8: https://github.com/schemaorg/schemaorg/blob/2cf65e15e41de98a86f20b64ff5e8657dad271b5/data/releases/3.8/ext-pending.rdf#L1020-L1031
* v7.04: https://github.com/schemaorg/schemaorg/blob/2cf65e15e41de98a86f20b64ff5e8657dad271b5/data/releases/7.04/ext-pending.rdf#L270-L281

**Comment by sascha-egerer** [comment]
Thank you for your detailed Feedback! Keep up the good work!
