### ISSUE TITLE
Up till which Schema.org Release this repo src is updated?

### ISSUE THREAD

**Issue by boospot** [spatie/schema-org#137]
Not an issue, but a question.

There are now release by Schema.org as described here:
https://schema.org/docs/releases.html

Is there any identification in the repo describing uptill which release version the **src** folder is updated?

Tried to look but could not find.

Thanks in advance

**Comment by Gummibeer** [comment]
Hey,

we have this on our map - right now we are on v7.04.
https://github.com/spatie/schema-org/blob/b1c88dc9744e70679a466b26432e8b85e4daac64/generator/Console/GenerateCommand.php#L34-L36

Because v8 would be a BC/major release we delay this until #133 is resolved.
One question in it is if we should build and deliver the extensions by default. If so, in a dedicated namespace each and possibly also a dedicated factory class or if we should stick to the basic schema definition.

**Comment by boospot** [comment]
Thanks @Gummibeer 

For the quick update. 

I wish i could give you some input on this but my php skills are below the **required** to comment on this.
