### ISSUE TITLE
Field geo for Hotel missing

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [spatie/schema-org#63]
Although https://schema.org/Hotel has a field "geo" it does not exist in this library (comes from Place). Is it because of PHP not supporting Multi Inheritance? If yes, perhaps traits could be used to better reflect schema.org's structure.

PS: Also applies for smokingAllowed.

**Comment by Gummibeer** [comment]
Which version do you use? This problem was fixed in [v2.0.0](https://github.com/spatie/schema-org/releases/tag/2.0.0).

Now `Hotel` mixins `LodgingBusiness` which mixins `LocalBusiness` which mixins `Place` which supports, like you said, the `geo` method:
https://github.com/spatie/schema-org/blob/ea9dc677d25fde535540fb4cd4c0ccdbc84732c3/src/Place.php#L197-L200

But even in v1 you still can call `geo()` and `smokingAllowed()` because they are catched `BaseType::__call` method which sets it as property:
https://github.com/spatie/schema-org/blob/ea9dc677d25fde535540fb4cd4c0ccdbc84732c3/src/BaseType.php#L122-L125

**Comment by BlackbitNeueMedien** [comment]
How does this work - actually I have never heard of a \@mixin annotation beside for supporting the IDE.
I am using the library to create a user interface where you can choose the microdata type of the page (therefore I fetch all classes in Spatie\SchemaOrg namespace and thereafter provide a form to input the fields (I do this with ReflectionClass to get all methods names (= input field labels) and parameters (which define input field types).
Is this still possible with version 2? Without the mixins e.g. Hotel microdata does not define any fields.

**Comment by BlackbitNeueMedien** [comment]
> Because with traits we would need round about 1.5 times the amount of classes/traits as now.

Seems a poor reason to me for not supporting autocompletion and reflection.
In fact the "cache" you propose actually would be the same files as when you used traits. So why put the load on every developer who uses this lib instead of simply providing a nice API?

**Comment by Gummibeer** [comment]
The cache won't create any file in your project (depending on cache-driver) but could be put into one file. So far I understood you want a list of all properties for one type. So even with Traits I recommend you to use a cache - reducing the reflection parse time from every request to one time during deployment.

But as I said: feel free to create a PR that brings traits instead of mixins. I think that your usecase isn't the common one for this package!? Primary because you are also abusing it a bit - you try to get a machine readable representation of the schema standard (that's already present as RDFA) to create a webinterface with forms. So even if it works it's not the primary usecase for this package - if it would be you would have methods like `getAvailableProperties()` and so on.

But the final decision is up to @sebastiandedeyne I think. And both ways I described are not rly hard to do, so you can:
* do it for your own
* create an extension package for this
* propose a PR
