### ISSUE TITLE
[RFC] Do not generate null values

### ISSUE THREAD

**Issue by kiler129** [spatie/schema-org#83]
### Introduction
I suggest we make a simple change in the library (maybe even with a flag?) where `BaseType` during dump (or even in `setProperty()`) simply ignores `null` values or

### Current status
As of now setting a null value on a field will cause the field to appear in the JSON-LD with `null` value.

### Reasoning
Mainstream tools seems blind to `null`ed fields like they never existed:
![image (2)](https://user-images.githubusercontent.com/1227834/58813689-ea857600-85e9-11e9-9681-501a24e0e09b.png)

This change would greatly improve DX, so that setters can be blindly called without `->if()`ing for everything. Such code as below:
```php
$mapLink = $this->gmapsFactory->linkFromGeo($company->getGeolocation());
$schema->if($mapLink !== null, function(LocalBusiness $schema) use ($mapLink): void {
    $schema->hasMap($mapLink);
});
```

Could be reduced to:
```php
$schema->hasMap($this->gmapsFactory->linkFromGeo($company->getGeolocation()));
```

WDYT?

**Comment by Gummibeer** [comment]
Without digging into it if there is a case where `null` is an expected value and what schema.org states. I would say that the setter itself could check this.
But like the discussion in #79 I would like to check if this is something really in the schema.org standard or if it's something related to JSON-LD or even only Google & Co.

Because this package is only a PHP OOP representation of the RDFA files and not targeted for any reader or something else we have to be careful and double-check where things like this really belong to and if they even belong to the goal of this package.

But I got your point, feel like it's an useful change and will try to find something but am also open for more input related to the underlying standard to help us with the decision.

**Comment by kiler129** [comment]
We did a lot of digging for our project and seems like `null `is a value which cannot appear in schema, since you cannot really represent it in other formats (e.g. RDF). I tried searching for explicit `null` mentions but I wasn't able to find anything besides "if you have no value don't provide the property".

The case of `null` doesn't seem to be described in any standard, the only knowledge we have so far is empirical - google treats missing property and property with `null` value as the same thing.
Because of that I would rather introduce this as a feature-flag enabled by default, we will get a report sooner than later if it breaks everything.

I mentioned RFC as a matter of "request-for-comments" from maintainers of the library here, not as an actual 3rd-party fomralized RFC.

**Comment by Gummibeer** [comment]
Ok, thanks for clarifying! After searching I also couldn't find any schema type property which accepts `null` as value.
So I think that it should be fine to prevent null values in general. Because this is theoretically breaking but also just a fix I would like to ask @sebastiandedeyne how he wants to release it!?

**Comment by kiler129** [comment]
@Gummibeer any word on that? :)

**Comment by Gummibeer** [comment]
Hey,
until now no word from @sebastiandedeyne . For me this is a Bugfix so we should be fine to do it in a minor release.
And it's a general schema thing so it should be done in `setProperty()` to prevent the `null` from getting into the data.
After nearly two weeks I would accept responsibility for it. So I will review/accept an incoming PR if you want to do it or do it myself otherwise and also release it.

**Comment by Gummibeer** [comment]
@kiler129 sorry for the long delay! It's now released https://github.com/spatie/schema-org/releases/tag/2.3.0 :)
