### ISSUE TITLE
Multiple types in one script tag

### ISSUE THREAD

**Issue by tarraq** [spatie/schema-org#94]

**Comment by tarraq** [comment]
Looking to do JSON-LD for a real estate agent and would like to do a double type of House and Product, as this example shows: https://schema.org/docs/hotels.html
`"@context": "http://schema.org/",
"@type": ["HotelRoom","Product"],`
Can the library do this?
Thanks for all the work you do!

**Comment by Gummibeer** [comment]
Hey, because we only extract the rdfa file there's no way to do this atm.
Have you checked if Google & co understand it?

We will have to check if there's a general standard that says that multiple types could be mixed or if there are only specific combination allowed. If there is no standard that describes it it will be hard to implement. If you can mix everything it's relatively easy to do. If there are only specific combinations allowed the rdfa file has to list them. Otherwise there's no way for us to solve it.

**Comment by tarraq** [comment]
I have not yet tried to validate it. Otherwise I'll just have to add two different entities and see how that plays out. Thank you.
